# Generated by Django 4.1.5 on 2023-01-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='title')),
                ('anons', models.CharField(max_length=250, verbose_name='beginning')),
                ('main_text', models.TextField(verbose_name='article')),
                ('date', models.DateField(verbose_name='date of publication')),
            ],
        ),
    ]
